
# Data source provided by user. 
# Format: {"name": "Display Name", "id": "Google ID", "gender": "MALE/FEMALE", "category": "Category"}

VOICE_DATA = {
    "Hindi": [
        {"id": "hi-IN-Chirp3-HD-Achernar", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Achird", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Algenib", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Algieba", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Alnilam", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Aoede", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Autonoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Callirrhoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Charon", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Despina", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Enceladus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Erinome", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Fenrir", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Gacrux", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Iapetus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Kore", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Laomedeia", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Leda", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Orus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Puck", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Pulcherrima", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Rasalgethi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Sadachbia", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Sadaltager", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Schedar", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Sulafat", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Umbriel", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Vindemiatrix", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Zephyr", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Chirp3-HD-Zubenelgenubi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "hi-IN-Neural2-A", "gender": "FEMALE", "category": "Neural2"},
        {"id": "hi-IN-Neural2-B", "gender": "MALE", "category": "Neural2"},
        {"id": "hi-IN-Neural2-C", "gender": "MALE", "category": "Neural2"},
        {"id": "hi-IN-Neural2-D", "gender": "FEMALE", "category": "Neural2"},
        {"id": "hi-IN-Standard-A", "gender": "FEMALE", "category": "Standard"},
        {"id": "hi-IN-Standard-B", "gender": "MALE", "category": "Standard"},
        {"id": "hi-IN-Standard-C", "gender": "MALE", "category": "Standard"},
        {"id": "hi-IN-Standard-D", "gender": "FEMALE", "category": "Standard"},
        {"id": "hi-IN-Standard-E", "gender": "FEMALE", "category": "Standard"},
        {"id": "hi-IN-Standard-F", "gender": "MALE", "category": "Standard"},
        {"id": "hi-IN-Wavenet-A", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "hi-IN-Wavenet-B", "gender": "MALE", "category": "Wavenet"},
        {"id": "hi-IN-Wavenet-C", "gender": "MALE", "category": "Wavenet"},
        {"id": "hi-IN-Wavenet-D", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "hi-IN-Wavenet-E", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "hi-IN-Wavenet-F", "gender": "MALE", "category": "Wavenet"},
    ],
    "Tamil": [
        {"id": "ta-IN-Chirp3-HD-Achernar", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Achird", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Algenib", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Algieba", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Alnilam", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Aoede", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Autonoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Callirrhoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Charon", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Despina", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Enceladus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Erinome", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Fenrir", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Gacrux", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Iapetus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Kore", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Laomedeia", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Leda", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Orus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Puck", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Pulcherrima", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Rasalgethi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Sadachbia", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Sadaltager", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Schedar", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Sulafat", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Umbriel", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Vindemiatrix", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Zephyr", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Chirp3-HD-Zubenelgenubi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ta-IN-Standard-A", "gender": "FEMALE", "category": "Standard"},
        {"id": "ta-IN-Standard-B", "gender": "MALE", "category": "Standard"},
        {"id": "ta-IN-Standard-C", "gender": "FEMALE", "category": "Standard"},
        {"id": "ta-IN-Standard-D", "gender": "MALE", "category": "Standard"},
        {"id": "ta-IN-Wavenet-A", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "ta-IN-Wavenet-B", "gender": "MALE", "category": "Wavenet"},
    ],
    "Telugu": [
        {"id": "te-IN-Chirp3-HD-Achernar", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Achird", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Algenib", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Algieba", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Alnilam", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Aoede", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Autonoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Callirrhoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Charon", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Despina", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Enceladus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Erinome", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Fenrir", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Gacrux", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Iapetus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Kore", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Laomedeia", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Leda", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Orus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Puck", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Pulcherrima", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Rasalgethi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Sadachbia", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Sadaltager", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Schedar", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Sulafat", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Umbriel", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Vindemiatrix", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Zephyr", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Chirp3-HD-Zubenelgenubi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "te-IN-Standard-A", "gender": "FEMALE", "category": "Standard"},
        {"id": "te-IN-Standard-B", "gender": "MALE", "category": "Standard"},
        {"id": "te-IN-Standard-C", "gender": "FEMALE", "category": "Standard"},
        {"id": "te-IN-Standard-D", "gender": "MALE", "category": "Standard"},
    ],
    "Kannada": [
        {"id": "kn-IN-Chirp3-HD-Achernar", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Achird", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Algenib", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Algieba", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Alnilam", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Aoede", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Autonoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Callirrhoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Charon", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Despina", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Enceladus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Erinome", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Fenrir", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Gacrux", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Iapetus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Kore", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Laomedeia", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Leda", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Orus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Puck", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Pulcherrima", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Rasalgethi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Sadachbia", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Sadaltager", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Schedar", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Sulafat", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Umbriel", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Vindemiatrix", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Zephyr", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Chirp3-HD-Zubenelgenubi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "kn-IN-Standard-A", "gender": "FEMALE", "category": "Standard"},
        {"id": "kn-IN-Standard-B", "gender": "MALE", "category": "Standard"},
        {"id": "kn-IN-Standard-C", "gender": "FEMALE", "category": "Standard"},
        {"id": "kn-IN-Standard-D", "gender": "MALE", "category": "Standard"},
        {"id": "kn-IN-Wavenet-A", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "kn-IN-Wavenet-B", "gender": "MALE", "category": "Wavenet"},
        {"id": "kn-IN-Wavenet-C", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "kn-IN-Wavenet-D", "gender": "MALE", "category": "Wavenet"},
    ],
    "Malayalam": [
        {"id": "ml-IN-Chirp3-HD-Achernar", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Achird", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Algenib", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Algieba", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Alnilam", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Aoede", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Autonoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Callirrhoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Charon", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Despina", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Enceladus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Erinome", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Fenrir", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Gacrux", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Iapetus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Kore", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Laomedeia", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Leda", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Orus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Puck", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Pulcherrima", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Rasalgethi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Sadachbia", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Sadaltager", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Schedar", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Sulafat", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Umbriel", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Vindemiatrix", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Zephyr", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Chirp3-HD-Zubenelgenubi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "ml-IN-Standard-A", "gender": "FEMALE", "category": "Standard"},
        {"id": "ml-IN-Standard-B", "gender": "MALE", "category": "Standard"},
        {"id": "ml-IN-Standard-C", "gender": "FEMALE", "category": "Standard"},
        {"id": "ml-IN-Standard-D", "gender": "MALE", "category": "Standard"},
        {"id": "ml-IN-Wavenet-A", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "ml-IN-Wavenet-B", "gender": "MALE", "category": "Wavenet"},
        {"id": "ml-IN-Wavenet-C", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "ml-IN-Wavenet-D", "gender": "MALE", "category": "Wavenet"},
    ],
    "Gujarati": [
        {"id": "gu-IN-Chirp3-HD-Achernar", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Achird", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Algenib", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Algieba", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Alnilam", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Aoede", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Autonoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Callirrhoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Charon", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Despina", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Enceladus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Erinome", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Fenrir", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Gacrux", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Iapetus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Kore", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Laomedeia", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Leda", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Orus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Puck", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Pulcherrima", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Rasalgethi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Sadachbia", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Sadaltager", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Schedar", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Sulafat", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Umbriel", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Vindemiatrix", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Zephyr", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Chirp3-HD-Zubenelgenubi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "gu-IN-Standard-A", "gender": "FEMALE", "category": "Standard"},
        {"id": "gu-IN-Standard-B", "gender": "MALE", "category": "Standard"},
        {"id": "gu-IN-Standard-C", "gender": "FEMALE", "category": "Standard"},
        {"id": "gu-IN-Standard-D", "gender": "MALE", "category": "Standard"},
        {"id": "gu-IN-Wavenet-A", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "gu-IN-Wavenet-B", "gender": "MALE", "category": "Wavenet"},
        {"id": "gu-IN-Wavenet-C", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "gu-IN-Wavenet-D", "gender": "MALE", "category": "Wavenet"},
    ],
    "Punjabi": [
        {"id": "pa-IN-Chirp3-HD-Achernar", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Achird", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Algenib", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Algieba", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Alnilam", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Aoede", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Autonoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Callirrhoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Charon", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Despina", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Enceladus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Erinome", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Fenrir", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Gacrux", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Iapetus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Kore", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Laomedeia", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Leda", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Orus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Puck", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Pulcherrima", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Rasalgethi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Sadachbia", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Sadaltager", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Schedar", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Sulafat", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Umbriel", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Vindemiatrix", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Zephyr", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Chirp3-HD-Zubenelgenubi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "pa-IN-Standard-A", "gender": "FEMALE", "category": "Standard"},
        {"id": "pa-IN-Standard-B", "gender": "MALE", "category": "Standard"},
        {"id": "pa-IN-Standard-C", "gender": "FEMALE", "category": "Standard"},
        {"id": "pa-IN-Standard-D", "gender": "MALE", "category": "Standard"},
        {"id": "pa-IN-Wavenet-A", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "pa-IN-Wavenet-B", "gender": "MALE", "category": "Wavenet"},
        {"id": "pa-IN-Wavenet-C", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "pa-IN-Wavenet-D", "gender": "MALE", "category": "Wavenet"},
    ],
    "Marathi": [
        {"id": "mr-IN-Chirp3-HD-Achernar", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Achird", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Algenib", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Algieba", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Alnilam", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Aoede", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Autonoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Callirrhoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Charon", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Despina", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Enceladus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Erinome", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Fenrir", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Gacrux", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Iapetus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Kore", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Laomedeia", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Leda", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Orus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Puck", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Pulcherrima", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Rasalgethi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Sadachbia", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Sadaltager", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Schedar", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Sulafat", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Umbriel", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Vindemiatrix", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Zephyr", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Chirp3-HD-Zubenelgenubi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "mr-IN-Standard-A", "gender": "FEMALE", "category": "Standard"},
        {"id": "mr-IN-Standard-B", "gender": "MALE", "category": "Standard"},
        {"id": "mr-IN-Standard-C", "gender": "FEMALE", "category": "Standard"},
        {"id": "mr-IN-Wavenet-A", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "mr-IN-Wavenet-B", "gender": "MALE", "category": "Wavenet"},
        {"id": "mr-IN-Wavenet-C", "gender": "FEMALE", "category": "Wavenet"},
    ],
    "Bengali": [
        {"id": "bn-IN-Chirp3-HD-Achernar", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Achird", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Algenib", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Algieba", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Alnilam", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Aoede", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Autonoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Callirrhoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Charon", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Despina", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Enceladus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Erinome", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Fenrir", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Gacrux", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Iapetus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Kore", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Laomedeia", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Leda", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Orus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Puck", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Pulcherrima", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Rasalgethi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Sadachbia", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Sadaltager", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Schedar", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Sulafat", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Umbriel", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Vindemiatrix", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Zephyr", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Chirp3-HD-Zubenelgenubi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "bn-IN-Standard-A", "gender": "FEMALE", "category": "Standard"},
        {"id": "bn-IN-Standard-B", "gender": "MALE", "category": "Standard"},
        {"id": "bn-IN-Standard-C", "gender": "FEMALE", "category": "Standard"},
        {"id": "bn-IN-Standard-D", "gender": "MALE", "category": "Standard"},
        {"id": "bn-IN-Wavenet-A", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "bn-IN-Wavenet-B", "gender": "MALE", "category": "Wavenet"},
        {"id": "bn-IN-Wavenet-C", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "bn-IN-Wavenet-D", "gender": "MALE", "category": "Wavenet"},
    ],
    "English": [
        {"id": "en-IN-Chirp-HD-D", "gender": "MALE", "category": "Chirp HD"},
        {"id": "en-IN-Chirp-HD-F", "gender": "FEMALE", "category": "Chirp HD"},
        {"id": "en-IN-Chirp-HD-O", "gender": "FEMALE", "category": "Chirp HD"},
        {"id": "en-IN-Chirp3-HD-Achernar", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Achird", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Algenib", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Algieba", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Alnilam", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Aoede", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Autonoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Callirrhoe", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Charon", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Despina", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Enceladus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Erinome", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Fenrir", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Gacrux", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Iapetus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Kore", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Laomedeia", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Leda", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Orus", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Puck", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Pulcherrima", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Rasalgethi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Sadachbia", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Sadaltager", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Schedar", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Sulafat", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Umbriel", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Vindemiatrix", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Zephyr", "gender": "FEMALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Chirp3-HD-Zubenelgenubi", "gender": "MALE", "category": "Chirp 3 HD"},
        {"id": "en-IN-Neural2-A", "gender": "FEMALE", "category": "Neural2"},
        {"id": "en-IN-Neural2-B", "gender": "MALE", "category": "Neural2"},
        {"id": "en-IN-Neural2-C", "gender": "MALE", "category": "Neural2"},
        {"id": "en-IN-Neural2-D", "gender": "FEMALE", "category": "Neural2"},
        {"id": "en-IN-Standard-A", "gender": "FEMALE", "category": "Standard"},
        {"id": "en-IN-Standard-B", "gender": "MALE", "category": "Standard"},
        {"id": "en-IN-Standard-C", "gender": "MALE", "category": "Standard"},
        {"id": "en-IN-Standard-D", "gender": "FEMALE", "category": "Standard"},
        {"id": "en-IN-Standard-E", "gender": "FEMALE", "category": "Standard"},
        {"id": "en-IN-Standard-F", "gender": "MALE", "category": "Standard"},
        {"id": "en-IN-Wavenet-A", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "en-IN-Wavenet-B", "gender": "MALE", "category": "Wavenet"},
        {"id": "en-IN-Wavenet-C", "gender": "MALE", "category": "Wavenet"},
        {"id": "en-IN-Wavenet-D", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "en-IN-Wavenet-E", "gender": "FEMALE", "category": "Wavenet"},
        {"id": "en-IN-Wavenet-F", "gender": "MALE", "category": "Wavenet"},
    ]
}
